name: 'PRs Size Labeler'
description: 'Sample GitHub Action written in Go to visualize and optionally limit the size of your pull requests'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  thresholds:
    description: 'Fail if the PR size is XL'
    required: false
    default: ''
  exclude_paths:
    description: 'Comment added if the PR size is XL'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.thresholds }}
    - ${{ inputs.exclude_paths }}
branding:
  icon: 'tag'
  color: 'green'