name: 'PRs Size Labeler'
description: 'GitHub Action to label Pull Requests based on size '
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  thresholds:
    description: 'Set the size thresholds or labels to apply.'
    required: false
    default: ''
  exclude_paths:
    description: 'Glob filepaths to exclude from size calcuation.'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.thresholds }}
    - ${{ inputs.exclude_paths }}
branding:
  icon: 'tag'
  color: 'green'